/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * cicada
 * OpenAPI spec version: 0.1.0
 */

export interface AgentInfo {
  agent_id: string;
  asn: string;
  asn_org: string;
  city: string;
  country_code: string;
  hostname: string;
  ip: string;
  kernel_version: string;
  os_type: string;
  os_version: string;
  region: string;
  remote_host: string;
  username: string;
}
