/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * cicada
 * OpenAPI spec version: 0.1.0
 */
import type { UserRole } from "./userRole";

export interface CurrentUserResponse {
  id: string;
  points: number;
  role: UserRole;
  username: string;
}
