/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * cicada
 * OpenAPI spec version: 0.1.0
 */

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const UserRole = {
  admin: "admin",
  user: "user",
} as const;
